### ISSUE TITLE
Bootstrap the layout

### ISSUE THREAD

**Issue by shidhincr** [shidhincr/MaterialCalc#1]
@tedscape  This is for you .. :)

**Comment by tedscape** [comment]
@shidhincr Just got my macbook. Starting soon.

**Comment by shidhincr** [comment]
Let's start a new branch and open the PR

**Comment by tedscape** [comment]
cool

**Comment by tedscape** [comment]
@shidhincr What's next?

**Comment by shidhincr** [comment]
@tedscape I don't have internet at home ( because moved to a new apartment ) .. Hopefully will get by this week.. I'll call you once I get it and then we can discuss
